RetinaFace:
    onnx_file:     "../mnet_cov2.onnx"
    engine_file:   "../mnet_cov2.trt"
    BATCH_SIZE:    1
    INPUT_CHANNEL: 3
    IMAGE_WIDTH:   640
    IMAGE_HEIGHT:  640
    obj_threshold: 0.5
    nms_threshold: 0.45
    detect_mask:   True
    mask_thresh:   0.5
    landmark_std:  0.2
    feature_steps: [32, 16, 8]
    anchor_sizes:  [[512, 256], [128, 64], [32, 16]]
